
import { StockMetadata } from '../types';

export const NSE_WATCHLIST: StockMetadata[] = [
  // Nifty 50 (Large Cap)
   { symbol: "ADANIENT", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "ADANIPORTS", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "APOLLOHOSP", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "ASIANPAINT", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "AXISBANK", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "BAJAJ-AUTO", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "BAJAJFINSV", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "BAJFINANCE", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "BHARTIARTL", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "BPCL", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "BRITANNIA", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "CIPLA", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "COALINDIA", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "DIVISLAB", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "DRREDDY", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "EICHERMOT", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "GRASIM", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "HCLTECH", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "HDFCBANK", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "HDFCLIFE", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "HEROMOTOCO", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "HINDALCO", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "HINDUNILVR", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "ICICIBANK", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "ITC", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "INDUSINDBK", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "INFY", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "JSWSTEEL", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "KOTAKBANK", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "LT", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "LTIM", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "M&M", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "MARUTI", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "NESTLEIND", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "NTPC", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "ONGC", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "POWERGRID", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "RELIANCE", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "SBIN", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "SUNPHARMA", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "TATACONSUM", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "TATAMOTORS", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "TATASTEEL", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "TCS", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "TECHM", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "TITAN", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "ULTRACEMCO", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "UPL", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  { symbol: "WIPRO", industry: "Unknown", index: "Nifty 50", marketCap: "Large" },
  
  // Nifty Next 50 (Mid Cap)
 { symbol: "ABB", industry: "Unknown", index: "Nifty Next 50", marketCap: "Mid" },
  { symbol: "ADANIPOWER", industry: "Unknown", index: "Nifty Next 50", marketCap: "Mid" },
  { symbol: "ADANIGREEN", industry: "Unknown", index: "Nifty Next 50", marketCap: "Mid" },
  { symbol: "ATGL", industry: "Unknown", index: "Nifty Next 50", marketCap: "Mid" },
  { symbol: "AMBUJACEM", industry: "Unknown", index: "Nifty Next 50", marketCap: "Mid" },
  { symbol: "BANKBARODA", industry: "Unknown", index: "Nifty Next 50", marketCap: "Mid" },
  { symbol: "BANDHANBNK", industry: "Unknown", index: "Nifty Next 50", marketCap: "Mid" },
  { symbol: "BERGEPAINT", industry: "Unknown", index: "Nifty Next 50", marketCap: "Mid" },
  { symbol: "BIOCON", industry: "Unknown", index: "Nifty Next 50", marketCap: "Mid" },
  { symbol: "BOSCHLTD", industry: "Unknown", index: "Nifty Next 50", marketCap: "Mid" },
  { symbol: "CANBK", industry: "Unknown", index: "Nifty Next 50", marketCap: "Mid" },
  { symbol: "CHOLAFIN", industry: "Unknown", index: "Nifty Next 50", marketCap: "Mid" },
  { symbol: "COLPAL", industry: "Unknown", index: "Nifty Next 50", marketCap: "Mid" },
  { symbol: "DLF", industry: "Unknown", index: "Nifty Next 50", marketCap: "Mid" },
  { symbol: "DMART", industry: "Unknown", index: "Nifty Next 50", marketCap: "Mid" },
  { symbol: "GAIL", industry: "Unknown", index: "Nifty Next 50", marketCap: "Mid" },
  { symbol: "GODREJCP", industry: "Unknown", index: "Nifty Next 50", marketCap: "Mid" },
  { symbol: "HAVELLS", industry: "Unknown", index: "Nifty Next 50", marketCap: "Mid" },
  { symbol: "HINDPETRO", industry: "Unknown", index: "Nifty Next 50", marketCap: "Mid" },
  { symbol: "ICICIPRULI", industry: "Unknown", index: "Nifty Next 50", marketCap: "Mid" },
  { symbol: "IGL", industry: "Unknown", index: "Nifty Next 50", marketCap: "Mid" },
  { symbol: "INDIGO", industry: "Unknown", index: "Nifty Next 50", marketCap: "Mid" },
  { symbol: "JINDALSTEL", industry: "Unknown", index: "Nifty Next 50", marketCap: "Mid" },
  { symbol: "LICI", industry: "Unknown", index: "Nifty Next 50", marketCap: "Mid" },
  { symbol: "LUPIN", industry: "Unknown", index: "Nifty Next 50", marketCap: "Mid" },
  { symbol: "MARICO", industry: "Unknown", index: "Nifty Next 50", marketCap: "Mid" },
  { symbol: "MUTHOOTFIN", industry: "Unknown", index: "Nifty Next 50", marketCap: "Mid" },
  { symbol: "NMDC", industry: "Unknown", index: "Nifty Next 50", marketCap: "Mid" },
  { symbol: "PEL", industry: "Unknown", index: "Nifty Next 50", marketCap: "Mid" },
  { symbol: "PNB", industry: "Unknown", index: "Nifty Next 50", marketCap: "Mid" },
  { symbol: "REC", industry: "Unknown", index: "Nifty Next 50", marketCap: "Mid" },
  { symbol: "SAIL", industry: "Unknown", index: "Nifty Next 50", marketCap: "Mid" },
  { symbol: "SBICARD", industry: "Unknown", index: "Nifty Next 50", marketCap: "Mid" },
  { symbol: "SIEMENS", industry: "Unknown", index: "Nifty Next 50", marketCap: "Mid" },
  { symbol: "SRF", industry: "Unknown", index: "Nifty Next 50", marketCap: "Mid" },
  { symbol: "TORNTPHARM", industry: "Unknown", index: "Nifty Next 50", marketCap: "Mid" },
  { symbol: "TVSMOTOR", industry: "Unknown", index: "Nifty Next 50", marketCap: "Mid" },
  { symbol: "UBL", industry: "Unknown", index: "Nifty Next 50", marketCap: "Mid" },
  { symbol: "VEDL", industry: "Unknown", index: "Nifty Next 50", marketCap: "Mid" },
  { symbol: "VOLTAS", industry: "Unknown", index: "Nifty Next 50", marketCap: "Mid" },
  { symbol: "WHIRLPOOL", industry: "Unknown", index: "Nifty Next 50", marketCap: "Mid" },
  { symbol: "YESBANK", industry: "Unknown", index: "Nifty Next 50", marketCap: "Mid" },

  //MID150
  { symbol: "AARTIIND", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "ABFRL", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "APLAPOLLO", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "ASTRAL", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "AUROPHARMA", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "AVANTIFEED", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "BALKRISIND", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "BATAINDIA", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "BHARATFORG", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "BHEL", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "BRIGADE", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "CANFINHOME", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "CASTROLIND", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "CENTRALBK", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "CHAMBLFERT", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "COFORGE", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "CUMMINSIND", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "CYIENT", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "DEEPAKNTR", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "DELHIVERY", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "DIXON", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "DRL", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "ESCORTS", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "EXIDEIND", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "FEDERALBNK", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "GODREJPROP", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "GUJGASLTD", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "HINDCOPPER", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "ICICIGI", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "IDFCFIRSTB", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "INDHOTEL", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "IRCTC", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "JSWENERGY", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "KEC", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "LALPATHLAB", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "LTF", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "MANKIND", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "MFSL", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "MGL", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "MPHASIS", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "NATIONALUM", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "NHPC", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "OBEROIRLTY", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "OFSS", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "PFC", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "PNBHOUSING", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "POLYCAB", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "PRESTIGE", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "RAMCOCEM", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "SAIL", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "SCHAEFFLER", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "SUNTV", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "SUPREMEIND", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "TATACHEM", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "TATAPOWER", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "TORNTPOWER", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "TRENT", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "TVSMOTOR", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "UBL", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "UNIONBANK", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "UPL", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "VOLTAS", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  { symbol: "ZOMATO", industry: "Unknown", index: "Nifty Midcap 150", marketCap: "Mid" },
  
  // Small Cap (Simulated)
 { symbol: "AFFLE", industry: "Unknown", index: "Nifty Smallcap 100", marketCap: "Small" },
  { symbol: "ANURAS", industry: "Unknown", index: "Nifty Smallcap 100", marketCap: "Small" },
  { symbol: "APARINDS", industry: "Unknown", index: "Nifty Smallcap 100", marketCap: "Small" },
  { symbol: "ASTERDM", industry: "Unknown", index: "Nifty Smallcap 100", marketCap: "Small" },
  { symbol: "BASF", industry: "Unknown", index: "Nifty Smallcap 100", marketCap: "Small" },
  { symbol: "BIRLACORPN", industry: "Unknown", index: "Nifty Smallcap 100", marketCap: "Small" },
  { symbol: "BLUEDART", industry: "Unknown", index: "Nifty Smallcap 100", marketCap: "Small" },
  { symbol: "CAMS", industry: "Unknown", index: "Nifty Smallcap 100", marketCap: "Small" },
  { symbol: "CARBORUNIV", industry: "Unknown", index: "Nifty Smallcap 100", marketCap: "Small" },
  { symbol: "CEATLTD", industry: "Unknown", index: "Nifty Smallcap 100", marketCap: "Small" },
  { symbol: "CHENNPETRO", industry: "Unknown", index: "Nifty Smallcap 100", marketCap: "Small" },
  { symbol: "CUB", industry: "Unknown", index: "Nifty Smallcap 100", marketCap: "Small" },
  { symbol: "DCMSHRIRAM", industry: "Unknown", index: "Nifty Smallcap 100", marketCap: "Small" },
  { symbol: "DELTACORP", industry: "Unknown", index: "Nifty Smallcap 100", marketCap: "Small" },
  { symbol: "EIDPARRY", industry: "Unknown", index: "Nifty Smallcap 100", marketCap: "Small" },
  { symbol: "EPL", industry: "Unknown", index: "Nifty Smallcap 100", marketCap: "Small" },
  { symbol: "FSL", industry: "Unknown", index: "Nifty Smallcap 100", marketCap: "Small" },
  { symbol: "GEPIL", industry: "Unknown", index: "Nifty Smallcap 100", marketCap: "Small" },
  { symbol: "GRINDWELL", industry: "Unknown", index: "Nifty Smallcap 100", marketCap: "Small" },
  { symbol: "HATSUN", industry: "Unknown", index: "Nifty Smallcap 100", marketCap: "Small" },
  { symbol: "HINDCOPPER", industry: "Unknown", index: "Nifty Smallcap 100", marketCap: "Small" },
  { symbol: "IDBI", industry: "Unknown", index: "Nifty Smallcap 100", marketCap: "Small" },
  { symbol: "IFBIND", industry: "Unknown", index: "Nifty Smallcap 100", marketCap: "Small" },
  { symbol: "IRB", industry: "Unknown", index: "Nifty Smallcap 100", marketCap: "Small" },
  { symbol: "JWL", industry: "Unknown", index: "Nifty Smallcap 100", marketCap: "Small" },
  { symbol: "KNRCON", industry: "Unknown", index: "Nifty Smallcap 100", marketCap: "Small" },
  { symbol: "KPITTECH", industry: "Unknown", index: "Nifty Smallcap 100", marketCap: "Small" },
  { symbol: "MCX", industry: "Unknown", index: "Nifty Smallcap 100", marketCap: "Small" },
  { symbol: "MRPL", industry: "Unknown", index: "Nifty Smallcap 100", marketCap: "Small" },
  { symbol: "NCC", industry: "Unknown", index: "Nifty Smallcap 100", marketCap: "Small" },
  { symbol: "OLECTRA", industry: "Unknown", index: "Nifty Smallcap 100", marketCap: "Small" },
  { symbol: "PCBL", industry: "Unknown", index: "Nifty Smallcap 100", marketCap: "Small" },
  { symbol: "RITES", industry: "Unknown", index: "Nifty Smallcap 100", marketCap: "Small" },
  { symbol: "SJVN", industry: "Unknown", index: "Nifty Smallcap 100", marketCap: "Small" },
  { symbol: "SOBHA", industry: "Unknown", index: "Nifty Smallcap 100", marketCap: "Small" },
  { symbol: "SONATSOFTW", industry: "Unknown", index: "Nifty Smallcap 100", marketCap: "Small" },
  { symbol: "STAR", industry: "Unknown", index: "Nifty Smallcap 100", marketCap: "Small" },
  { symbol: "TATAELXSI", industry: "Unknown", index: "Nifty Smallcap 100", marketCap: "Small" },
  { symbol: "TATAMETALI", industry: "Unknown", index: "Nifty Smallcap 100", marketCap: "Small" },
  { symbol: "UJJIVAN", industry: "Unknown", index: "Nifty Smallcap 100", marketCap: "Small" },
  { symbol: "WELSPUNIND", industry: "Unknown", index: "Nifty Smallcap 100", marketCap: "Small" },
  { symbol: "ZEEL", industry: "Unknown", index: "Nifty Smallcap 100", marketCap: "Small" },

];

export const INDUSTRIES = Array.from(new Set(NSE_WATCHLIST.map(s => s.industry))).sort();
export const INDICES = ["Nifty 50", "Nifty Next 50", "Nifty Smallcap 100", "Nifty Midcap 150"];
